import Head from "next/head";
import Navbar from "@/components/Navbar";
import { Box, Container } from "@chakra-ui/react";

export default function Home() {
  return (
    <>
      <Head>
        <title>CropLink</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Navbar />
        <Container maxW={"7xl"} mt="10">
          Home page
        </Container>
      </Box>
    </>
  );
}
